"""
Application colors for tkinter, not for users
"""

MAIN_DARK_GRAY = "#333"
ACTIVE_MENU = "#444"
INACTIVE_CANVAS = "#aaa"
ACTIVE_CANVAS = "#ddd"
BUTTON_ACTIVE_BG = "#ccc"
BUTTON_ACTIVE_FG = "#333"
ACTIVE_TEXT = "#fff"
NODE_COLOR = "#fff"
EDGE_COLOR = "#000"
BST_LT_EDGE = "#00f"
BST_GT_EDGE = "#f00"
BST_EQ_EDGE = "#0f0"
CONSOLE_BG = "#fff"
TEXTBOX_BG = "#fff"
TEXTBOX_BORDER = "#000"
ARROW_FILL = "#000"
